sudo: required
language: scala

jdk:
- openjdk8

services:
- docker
- postgresql

addons:
  postgresql: "9.5"

cache:
  directories:
  - $HOME/.m2

env:
  global:
  # ARTIFACTORY_USERNAME
  - secure: "LwiHc/AFU+mVlh/iU2TvjLGOBX51uGP8Mjsjfw56Igc3ON+eAjAxxw05TNlVXzNo/LWu911S3UV4Nu1fyAsSNVyqy49DXJvIU6m4ddNGZTFjap/vxZvdPbRG4tZgaJiTf1UOaYWx3WglGXzezYMfYdwlIMrNKdImqagwVcH94GU="
  # ARTIFACTORY_PASSWORD
  - secure: "py3TMdAOOnfCWYPVTPBxUkVyfT3JeJBlkHXFEM9Dn+tdyTEdKXX4Mz/EK223MZsk3Kk/ktpccYeWBR+NX7xC0WOS2MQIw7e8Owuub6Nb6wBc93sqzGrWbqmg+y0iRVPuC78TQpS5yB5IFrYB1EJGlpNsw+Rkabp7Wi25tcHFuyk="
  # AWS_ACCESS_KEY_ID
  - secure: "aLQMwS4FpxVEElegI9K/0cJHU+lFetfIdyRhpTljl/irh7DJFgFoxXKHVmkYSvf6HINHa949Yk8NuSBagHUac5qqjgWwfKzM1A60f3diypLGKf/a3DcWmqv8jV3KBROSq3zWVxtkgQ7lOGyQQsj63pAqsRnaiaIIreqP+8LZZtw="
  # AWS_SECRET_ACCESS_KEY
  - secure: "IR/3UAQTb4epWh5Sl0pcutGy3E1G9mjR5tiW23fjWEM3HM/ihtCRtuvjXyK89JBt8OJoYaUXW21KD9C8q10oNUNMVhZqHkA5n8s6dngK3/WysFLNx7aZYsosRjRmUqgja1iRdA4x5kgMgQiQz5Ugi0QgomMmMvekw6LJyQHsKnw="

install:
- export TZ=Europe/Helsinki
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh

before_script:
- DB_NAME=valintarekisteri
- psql -c "create database $DB_NAME;" -U postgres
- psql -d $DB_NAME -f valinta-tulos-valintarekisteri-db/postgresql/init_it_postgresql.sql

script:
- mvn -B -Dvalintatulos.it.postgres.port=5432 -Dvalintatulos.it.postgres.alreadyrunning=true clean package

- export BASE_IMAGE="baseimage-war-openjdk8:master"
- ./ci-tools/common/pull-image.sh

- mv valinta-tulos-service/target/valinta-tulos-service-*.war $DOCKER_BUILD_DIR/artifact/valinta-tulos-service.war
- cp -vr valinta-tulos-service/src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/
- ./ci-tools/build/build-war.sh valinta-tulos-service

- ./ci-tools/common/clean-docker-build-dir.sh
- export BASE_IMAGE="baseimage-fatjar-openjdk8:master"
- ./ci-tools/common/pull-image.sh
- mv valinta-tulos-henkiloviite-synchronizer/target/valinta-tulos-henkiloviite-synchronizer-*-jar-with-dependencies.jar $DOCKER_BUILD_DIR/artifact/valinta-tulos-henkiloviite-synchronizer.jar
- cp -vr valinta-tulos-henkiloviite-synchronizer/target/classes/oph-configuration $DOCKER_BUILD_DIR/config/
- ./ci-tools/build/build-fatjar.sh valinta-tulos-henkiloviite-synchronizer

deploy:
  - provider: script
    script:
      mvn deploy -pl fi.vm.sade:valinta-tulos-service-parent,valinta-tulos-valintarekisteri-db,valinta-tulos-service -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script:
      ./ci-tools/build/upload-image.sh valinta-tulos-service;
      ./ci-tools/build/upload-image.sh valinta-tulos-henkiloviite-synchronizer
    on:
      all_branches: true
